### ISSUE TITLE
This is a suggestion!!!  - FOCUS READING LINE MODE

### ISSUE THREAD

**Issue by Jota-veh** [shigeyukey/AnkiArcade#24]
First and foremost, I want to say that I'm a huge fan of yours! Your plugins are incredibly useful, and AnkiArcade is the absolute best! I'm here with a plugin suggestion that I believe would be incredibly beneficial in various contexts. I wasn't sure how to contact you directly, so I decided to reach out here on your GitHub. You're the best Anki creator I've ever seen, and I've come across your comments about incremental reading in various forums.

Anyway, without further ado, the Microsoft Edge browser has a feature in reading mode where only the currently focused line of text is highlighted and clear, while the rest of the screen is shaded. This significantly enhances focus and helps prevent information overload. I can imagine how useful this would be for cards with dense information, as well as cards with two or three lines of text. Do you think it would be possible to create a plugin for this? I believe many in the community would appreciate the idea. I would personally be willing to pay for such a plugin, if that's an option. I've attached a GIF for your reference.

JS package if you are is interested with
https://github.com/KamilRizatdinov/reader_line
![FocusLineReading](https://github.com/shigeyukey/AnkiArcade/assets/96387624/7576df3f-5f3f-4e3a-a188-6e8e95075a4e)

**Comment by shigeyukey** [comment]
Thanks for the feedback and request! :-)
I found your thread on AnkiForums and will respond there.
https://forums.ankiweb.net/t/request-feature-line-reading-focus/46731
